/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Placement,
} from 'popper.js';

export namespace Components {
  interface DateCalender {
    'dateFormat': string;
    /**
    * The language code
    */
    'langCode': string;
    'selectedDate': string;
    'setParentSelectedDate': any;
  }
  interface DatepickerHijri {
    'langCode': string;
    'onDateChange': any;
    'placement': Placement;
    'reference': string;
    'selectedDate': string;
  }
  interface DayNames {
    /**
    * The language code
    */
    'langCode': string;
  }
  interface MonthDays {
    'currentTime': any;
    'dateFormat': any;
    'selectedDate': any;
    'setSelectedDate': any;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface ProperComponent {
    'langCode': string;
    'onDateChange': any;
    'placement': Placement;
    'reference': string;
    'selectedDate': string;
  }
}

declare global {


  interface HTMLDateCalenderElement extends Components.DateCalender, HTMLStencilElement {}
  const HTMLDateCalenderElement: {
    prototype: HTMLDateCalenderElement;
    new (): HTMLDateCalenderElement;
  };

  interface HTMLDatepickerHijriElement extends Components.DatepickerHijri, HTMLStencilElement {}
  const HTMLDatepickerHijriElement: {
    prototype: HTMLDatepickerHijriElement;
    new (): HTMLDatepickerHijriElement;
  };

  interface HTMLDayNamesElement extends Components.DayNames, HTMLStencilElement {}
  const HTMLDayNamesElement: {
    prototype: HTMLDayNamesElement;
    new (): HTMLDayNamesElement;
  };

  interface HTMLMonthDaysElement extends Components.MonthDays, HTMLStencilElement {}
  const HTMLMonthDaysElement: {
    prototype: HTMLMonthDaysElement;
    new (): HTMLMonthDaysElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  const HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLProperComponentElement extends Components.ProperComponent, HTMLStencilElement {}
  const HTMLProperComponentElement: {
    prototype: HTMLProperComponentElement;
    new (): HTMLProperComponentElement;
  };
  interface HTMLElementTagNameMap {
    'date-calender': HTMLDateCalenderElement;
    'datepicker-hijri': HTMLDatepickerHijriElement;
    'day-names': HTMLDayNamesElement;
    'month-days': HTMLMonthDaysElement;
    'my-component': HTMLMyComponentElement;
    'proper-component': HTMLProperComponentElement;
  }
}

declare namespace LocalJSX {
  interface DateCalender {
    'dateFormat'?: string;
    /**
    * The language code
    */
    'langCode'?: string;
    'selectedDate'?: string;
    'setParentSelectedDate'?: any;
  }
  interface DatepickerHijri {
    'langCode'?: string;
    'onDateChange'?: any;
    'placement'?: Placement;
    'reference'?: string;
    'selectedDate'?: string;
  }
  interface DayNames {
    /**
    * The language code
    */
    'langCode'?: string;
  }
  interface MonthDays {
    'currentTime'?: any;
    'dateFormat'?: any;
    'selectedDate'?: any;
    'setSelectedDate'?: any;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface ProperComponent {
    'langCode'?: string;
    'onDateChange'?: any;
    'placement'?: Placement;
    'reference'?: string;
    'selectedDate'?: string;
  }

  interface IntrinsicElements {
    'date-calender': DateCalender;
    'datepicker-hijri': DatepickerHijri;
    'day-names': DayNames;
    'month-days': MonthDays;
    'my-component': MyComponent;
    'proper-component': ProperComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'date-calender': LocalJSX.DateCalender & JSXBase.HTMLAttributes<HTMLDateCalenderElement>;
      'datepicker-hijri': LocalJSX.DatepickerHijri & JSXBase.HTMLAttributes<HTMLDatepickerHijriElement>;
      'day-names': LocalJSX.DayNames & JSXBase.HTMLAttributes<HTMLDayNamesElement>;
      'month-days': LocalJSX.MonthDays & JSXBase.HTMLAttributes<HTMLMonthDaysElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'proper-component': LocalJSX.ProperComponent & JSXBase.HTMLAttributes<HTMLProperComponentElement>;
    }
  }
}


